name: Deploy to GAE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: citric-gradient-439303-u3

    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --quiet
